### ISSUE TITLE
Search bar layout modification

### ISSUE THREAD

**Issue by Bbiswabasu** [Technical-Hackers/Health-Log#10]
The search bar is overlapping with doctor & patients' names. The search should be kept at the top of the page and list must start below that

**Comment by Bbiswabasu** [comment]
I want to work on this issue

**Comment by iamsh4shank** [comment]
Hello @Bbiswabasu I raised a similar issue (#1 ) for this, so you can close this issue and start working on that, I assigned you with that issue. Feel free to ask you doubts in the channel

**Comment by iamsh4shank** [comment]
Once comment on the #1 issue
