### ISSUE TITLE
Add settings page

### ISSUE THREAD

**Issue by iamsh4shank** [Technical-Hackers/Health-Log#24]
As of now, the app doesn't contain a settings page so a lot of improvements are pending because of that, so it would be great if anyone can add a settings button on the app bar just left to the logout button

**Comment by shivjyotigarai** [comment]
What should the settings button contain...?😊 @robustTechie

**Comment by iamsh4shank** [comment]
Hey, @shivjyotigarai you can add an edit language feature as the change language feature is already implemented, as of now you can do this then further we will add a theme editor and a few other cool stuff

**Comment by shivjyotigarai** [comment]
whats the diff between edit language and change language feature ?
@robustTechie

**Comment by iamsh4shank** [comment]
same

**Comment by codeDamon** [comment]
I like to work on this issue. 
Can you assgn this to me?

**Comment by iamsh4shank** [comment]
yeah you can work on this
