### ISSUE TITLE
Multi language support

### ISSUE THREAD

**Issue by iamsh4shank** [Technical-Hackers/Health-Log#4]
Add a few more languages to make it more usable across the globe

**Comment by shivjyotigarai** [comment]
want to work on this issue....

**Comment by iamsh4shank** [comment]
Yeah go ahead :)

**Comment by shivjyotigarai** [comment]
Added French, German and Spanish....will it do?

**Comment by Droyder7** [comment]
Hey @robustTechie @shivjyotigarai I also want to contribute to resolving this issue. I want add other languages which are not added like regional languages of India or any other global languages. So can please you assign this to me in order to do that?

**Comment by iamsh4shank** [comment]
Hello, @shivjyotigarai and @Droyder7 thank you for working on this localization issue. You both can work on the issue so @shivjyotigarai you can add the option inside the app to switch the language as you said you will add French, German, and Spanish. @Droyder7 you can create one another issue based on adding the regional languages. Is it fine?

**Comment by shivjyotigarai** [comment]
@robustTechie when the user will change the phones language to french/german/spanish etc from the settings...the app will automatically start in that particular language....

**Comment by iamsh4shank** [comment]
@shivjyotigarai you can do that too but adding a dedicated option to change the language in the app itself would be a great improvement in the app :)

**Comment by shivjyotigarai** [comment]
@robustTechie ok

**Comment by shivjyotigarai** [comment]
![image](https://user-images.githubusercontent.com/74768430/101471517-6a259b00-396d-11eb-828a-89c6e1bc4e34.png)
![image](https://user-images.githubusercontent.com/74768430/101471594-8590a600-396d-11eb-9b7f-e9e5162c60cc.png)
![image](https://user-images.githubusercontent.com/74768430/101471630-8f1a0e00-396d-11eb-8335-d34a70a17868.png)

DONE...its working fine :)

**Comment by shivjyotigarai** [comment]
plz see....generated a pull request regarding the same :)
