### ISSUE TITLE
Add an option to delete patient 

### ISSUE THREAD

**Issue by iamsh4shank** [Technical-Hackers/Health-Log#7]
Provide a feature to delete patient from the list

**Comment by sahil1678kumar** [comment]
I want to work on this

**Comment by iamsh4shank** [comment]
Hey, @sahil1678kumar  go ahead :) If you have any doubt feel free to ask in the channel

**Comment by Bbiswabasu** [comment]
Is anyone working on this? Otherwise I would like to do this

**Comment by iamsh4shank** [comment]
@sahil1678kumar any update on this :)
