### ISSUE TITLE
Add splash screen

### ISSUE THREAD

**Issue by iamsh4shank** [Technical-Hackers/Health-Log#9]
Add splash screen, before adding it to the main app you can put the suggested design in the comment :)

**Comment by ajaygalagali** [comment]
@robustTechie I want to work on this.

**Comment by ajaygalagali** [comment]
Proposed splash screen design. 

![splashScreen](https://user-images.githubusercontent.com/52245467/101308773-a2937f00-3870-11eb-9042-d089db42efa7.jpg)

**Comment by iamsh4shank** [comment]
Great work @ajaygalagali go ahead :)
Feel free to ask your doubts in the channel.
